### ISSUE TITLE
Floats or Rats?

### ISSUE THREAD

**Issue by druud** [pjacklam/p5-bignum#5]
Is this as should be expected?
```
% perl -Mstrict -wE 'say 0.1 + 0.2 == 0.3 ? "T" : "F"' 
F

% perl -Mstrict -MMath::BigInt -wE 'say 0.1 + 0.2 == 0.3 ? "T" : "F"'
F

% perl -Mstrict -Mbigint -wE 'say 0.1 + 0.2 == 0.3 ? "T" : "F"'
T
```

**Comment by pjacklam** [comment]
What you see is consistent with the documentation and how it is intended to work. In the first two cases, the floating point values are not affected at all. In the third case, the floating point values are converted to Math::BigInt objects representing the value zero. As we all know, 0 + 0 = 0.

You get the same result with the `bigfloat` pragma:
```
$ perl -Mstrict -Mbigfloat -wE 'say 0.1 + 0.2 == 0.3 ? "T" : "F"'
T
```
although in this case, the three floating point numbers are converted to Math::BigFloat objects representing the exact values 0.1, 0.2, and 0.3, respectively.

**Comment by druud** [comment]
ACK, my wrong assumption was that bigint only touches numeric values that start out as integer.

**Comment by pjacklam** [comment]
That behaviour (`bigint` ignoring non-integer numbers) shouldn't be difficult to implement. If I go for it, it will be optional, since the current behaviour has been the default for ages.
